# templates/configmap.yaml
{{- range .Values.containers }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-config
data:
  {{- range $key, $value := .config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
