# templates/ingress.yaml
{{- range .Values.containers }}
{{- if .ingress.enabled }}

{{- if .ingress.isOpenshiftRoute }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .name }}
spec:
  {{- if .ingress.host }}
  host: {{ .ingress.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ .name }} # Apunta al Service que creamos antes
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- else }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
spec:
  rules:
    - {{- if .ingress.host }}
      host: {{ .ingress.host }}
      {{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .name }} # Apunta al Service
                port:
                  number: {{ $.Values.service.port }}
{{- end }}
{{- end }}
{{- end }}
