apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  index.html: |
    <html>
    <h1>AIMS Mobile</h1>
    </br>
    <h1>AIMS Mobile - Microsafe</h1>
    </html
