apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: aims-http
    namespace: {{ .Values.namespace }}
  spec:
    clusterIP:
    clusterIPs:
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: aims-http
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: aims-ws
    namespace: {{ .Values.namespace }}
  spec:
    clusterIP:
    clusterIPs:
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app: aims-ws
    sessionAffinity: None
    type: ClusterIP
kind: List
metadata:
  resourceVersion: ""
